baseURL: ""
languageCode: en-us
title: HeapCreate
# theme: PaperMod
paginate: 5

enableRobotsTXT: true
enableInlineShortcodes: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: HeapCreate
  description: "HeapCreate"
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  # ShowWordCount: true
  defaultTheme: auto
  ShowCodeCopyButtons: true
  UseHugoToc: true
  # disableSpecial1stPost: false
  # disableScrollToTop: false
  # comments: false
  # hidemeta: false
  # hideSummary: false
  showtoc: true
  homeInfoParams:
    Title: "Hello strangers 👋"
    Content: "This place serves as my note and everything I learnt 🌲"
  socialIcons:
    - name: twitter
      url: "https://twitter.com/ahmadshauqi4"
    - name: github
      url: "https://github.com/nightfury99"
    - name: behance
      url: "https://www.behance.net/shauqiAppleDeveloper"
    - name: medium
      url: "https://medium.com/@shauqighost99"
  cover:
    linkFullImages: true
  # disableScrollToTop: true
  assets:
    favicon: "icons/heapcreate_icon.png"
  label:
    text: "HeapCreate"
    icon: icons/heapcreate_icon.png
    iconDark: icons/heapcreate_icon.png
    iconHeight: 20
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    # limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

menu:
  main:
    - identifier: home
      name: home
      url: /
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: archives
      url: /archives/
      weight: 30
    - identifier: search
      name: search
      url: /search/
      weight: 40
    - identifier: about
      name: about
      url: /about/
      weight: 50

security:
  funcs:
    getenv:
      - ^HUGO_
      - ^WC_

